baseURL = "https://www.yorickjacquin.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Yorick Jacquin"
theme = "hello-friend-ng"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "Yorick Jacquin"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "2 Jul, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "Ruby on Rails Freelance Developer"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # gitUrl = "https://github.com/username/repository/commit/"
  # Prefix of link to the git commit detail page. GitInfo must be enabled.

  [params.logo]
    logoText = "Available for a mission!"
  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "email"
    url = "mailto:yorickjacquin@gmail.com"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/yorick-jacquin-290702146/"

  [[params.social]]
    name = "github"
    url = "https://github.com/yjacquin"

  [[params.social]]
    name = "medium"
    url = "https://medium.com/@yorickjacquin"

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
